language: cpp
compiler:
- clang
- gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
			
before_install:
- echo CXX Version
- $CXX --version

script:
- mkdir build
- cd build
- cmake .. && cmake --build . && ctest ..
